### ISSUE TITLE
Take out "Exhibit" tab ?

### ISSUE THREAD

**Issue by kittyshi** [pianoroll/SUPRA#2]
As it's now linked from "Library portal"

**Comment by craigsapp** [comment]
Yes, I thought I had deleted it, but obviously not.  Now fixed:

<img width="766" alt="Screen Shot 2019-11-01 at 9 48 28 PM" src="https://user-images.githubusercontent.com/3487289/68066185-fee0b280-fcf0-11e9-9661-633f727bc1fc.png">
