### ISSUE TITLE
Feedback tab

### ISSUE THREAD

**Issue by kittyshi** [pianoroll/SUPRA#3]
- "Stats go here". pending

- The red underline is with "Home"  when on "Feedback tab".
It should be under "Feedback"

**Comment by craigsapp** [comment]
Fixed:

<img width="923" alt="Screen Shot 2019-11-01 at 9 37 26 PM" src="https://user-images.githubusercontent.com/3487289/68066070-7ca3be80-fcef-11e9-92db-7b91a6a66ede.png">

and

<img width="195" alt="Screen Shot 2019-11-01 at 9 37 59 PM" src="https://user-images.githubusercontent.com/3487289/68066074-875e5380-fcef-11e9-9059-d0561611d275.png">
